sudo: required
dist: trusty
language: node_js
node_js: stable

notifications:
  email: false
  
cache:
  directories: node_modules

addons:
apt:
  sources:
    - google-chrome

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
- npm prune
- npm uninstall typescript --no-save
- npm install --save typescript@2.1.1
- npm install --save codacy-coverage
- npm install --save @compodoc/compodoc
- npm install

before_script:
- ng lint
- ng build
- webdriver-manager update
- ng serve & ng e2e
- ng test --watch=false --code-coverage
- ./node_modules/.bin/compodoc -p ./src/tsconfig.app.json

script:
- cat ./coverage/coverage.lcov | ./node_modules/.bin/codacy-coverage --debug --language typescript

deploy:
  - provider: s3
    access_key_id: ${ARTIFACTS_KEY}
    secret_access_key: ${ARTIFACTS_SECRET}
    bucket: ustocktrade-documentation
    skip_cleanup: true
    upload-dir: documentation
    local_dir: documentation